export const datalar = [
  {
    id: "1",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/79619/joes-kc-ribs-brisket-and-burnt-ends.6710e994980e485e6441b794717ad6fb.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Joe's KC BBQ",
    dsc: "Joe's KC Ribs, Brisket & Burnt Ends",
    price: "110.99",
    rate: "5",
    country: "Kansas City, KS",
  },
  {
    id: "2",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/66752/carolina-bbq-oink-sampler.1340b5a10cedc238cb2280306dd1d5a5.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Kings BBQ",
    dsc: "Carolina BBQ Oink Sampler",
    price: 89,
    rate: 4,
    country: "Kinston, NC",
  },
  {
    id: "3",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/131249/texas-monthlys-1-bbq-brisket.1006a061be7acae03992e420fbca995a.png?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Snow's BBQ",
    dsc: "Texas Monthly's #1 BBQ Brisket",
    price: 199,
    rate: 5,
    country: "Lexington, TX",
  },
  {
    id: "4",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/137366/Central-BBQ-Ribs-Pulled-Pork-Dinner-1.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Central BBQ",
    dsc: "Ribs & Pulled Pork Dinner for 4",
    price: 79,
    rate: 5,
    country: "Memphis, TN",
  },
  {
    id: "5",
    img: "https://roadfood.com/wp-content/uploads/2021/09/Arthur-Bryant-rib-sandwich.jpg",
    name: "Arthur Bryant's Barbeque",
    dsc: "Barbeque Sampler for 8",
    price: 139,
    rate: 5,
    country: "Kansas City, MO",
  },
  {
    id: "6",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/110384/whole-brisket-texas-barbecue-bbq-sauce.e07ee4818b20ed43d217bf67fedd41ce.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Franklin Barbecue",
    dsc: "Whole Brisket + Texas Barbecue BBQ Sauce",
    price: 249,
    rate: 5,
    country: "Austin, TX",
  },
  {
    id: "7",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/101071/whole-texas-smoked-brisket.a5558a25381e271408e197936e7985d8.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Terry Black's Barbecue",
    dsc: "Whole Texas Smoked Brisket",
    price: 189,
    rate: 4,
    country: "Austin, TX",
  },
  {
    id: "8",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/137368/Central-BBQ-Ribs-Pulled-Pork-Party-Pack-1_.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Central BBQ",
    dsc: "Ribs & Pulled Pork Dinner for 8",
    price: 109,
    rate: 5,
    country: "Memphis, TN",
  },
  {
    id: "9",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/90406/mini-trinity-bbq-combo-brisket-ribs-and-links.245582f593bf64b23b57dfca2be18cfd.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Bludso's BBQ",
    dsc: "Mini Trinity BBQ Combo - Brisket, Ribs & Links",
    price: 139,
    rate: 5,
    country: "Los Angeles, CA",
  },
  {
    id: "10",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/113814/blue-smoke-baby-back-ribs-backyard-barbecue-chicken-combo.a95a3e632ae324f719738a2a5c1dff6e.png?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Blue Smoke",
    dsc: "Blue Smoke Baby Back Ribs + Backyard Barbecue Chicken Combo",
    price: 129,
    rate: 5,
    country: "New York, NY",
  },
  {
    id: "11",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/66734/bbq-meat-lovers-special-for-10.36ca670fda4bfa783c2ea9165e068d26.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Kings BBQ",
    dsc: "BBQ Meat Lovers Special for 10",
    price: 139,
    rate: 5,
    country: "Kinston, NC",
  },
  {
    id: "12",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/133378/choose-your-own-world-championship-bbq-4-pack.d5216e2b1c2a92f481fc9d1c7a15e8df.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Big Bob Gibson Bar-B-Q",
    dsc: "Choose Your Own World Championship BBQ - 4 Pack",
    price: 109.95,
    rate: 4,
    country: "Decatur, AL",
  },
  {
    id: "13",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/91821/best-of-texas-bbq-combo-serves-14.7ae90266335e539c67e77fed14b43029.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Snow's BBQ",
    dsc: "Best of Texas BBQ Combo - Serves 14",
    price: 269,
    rate: 4,
    country: "Lexington, TX",
  },
  {
    id: "14",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/134182/mighty-quinns-bbq-sampler-pack.1bfe4a0665edc565756f5241bf25840e.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Mighty Quinn's BBQ",
    dsc: "Mighty Quinn's BBQ Sampler Pack",
    price: 169,
    rate: 5,
    country: "New York, NY",
  },
  {
    id: "15",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132122/the-big-ugly-bbq-dinner-for-6.2dfae7818811adddce85cc1a910881a0.jpeg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Ugly Drum",
    dsc: "The Big Ugly BBQ Dinner for 6",
    price: 229,
    rate: 4,
    country: "Los Angeles, CA",
  },
];
